server:
 port: 8080

spring:
 application:
  name: selecaojava
 data:
  mongodb:
   uri: mongodb+srv://admin:HgV0iEkoFI6gMPvg@cluster0.fglkw.mongodb.net/selecaojava?retryWrites=true&w=majority

jwt:
  secret: c2VjcmV0S2V5